---
upgrade_packages: false

vm_config:
  memory: 1024
  cores: 1
  disk_size: "40G"
  disk_storage: "local-lvm"
  username: "vm"
  password: "password"
  hagroup: ""


pve_nodes:
  - jayesh

pve_credentials:
  api_endpoint: "https://192.168.29.29:8006/api2/json"
  api_token_id: "root@pam!ansibleT"
  api_secret: "131cad3d-2b50-4b2e-8ba0-3c37caa6a3de"

ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDT+ghI2UBlTab9xTeJOI9tMGEeTgukG7sCiofZIJrhliU/gJLbEQNNki7ha2JoFvVgZM8sBcFP6R0YMXZ4GL/c8riERK9/AdwKrlynSLWirUi2/yA1ucAr5c0Lx9KbWtNosa3sNV4m9kfboyF8a5t89aECmbCsW+uwCqDZgpSyr/42q8KcTJaZjRh0MZPsJW+aoUb4zJ9xEmqyP1/Z6qP2KEN3M4+lsmg4E///tL7ATRUkmSUoB3Kg16XRb7YW4YcuSbtZLgNriFj+jAgXQLj0zeKRjQdJuqzpxumsquPhBioheeyyT6X3PdEiewfQ+NkH+FbYlBYSiJCA6Qrssc26weszIFo5I/+5tUStiVBrzVCpczUlR90QB1gDsZPHDGgj3W5xJYRKEWFwjKaUhDMh2pWUOHu2uaeSdODQ1dhp8sncv2BzBOZtKmqXwrOOhUk/vHUcd6Ndpci20PBDpO2E2TPslkyaR1Mi5hoKhc5gWDSzK5HQC0mRliuJ6IiWtqc= jr@controller-vm"
ssh_private_key_path: "/home/ubuntu/.sshkey/cloudinit"

gateways:
  - uuid: codevm
    comments: "Customer 1 Inc."
    nodes:
      - ip_gateway: 192.168.29.1
        ip_address: 192.168.29.91
        ip_cidr: 24
    dns: 127.0.1.1
    state: present
